# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Stochastic Gradient Descent (SGD) algorithm for Support Vector Machines (SVM) using C++
#'
#' @param X, y of input data
#' @param epochs number of epochs
#' @param C regularization parameter
#' @param learning_rate learning rate
#' @param tolerance for stopping criterion
#' @return weight w and bias b
#' @export
svm_sgd_Rcpp <- function(X, y, epochs, C = 1.0, learning_rate = 1e-2, tolerance = 1e-3) {
    .Call(`_SVMalgo_svm_sgd_Rcpp`, X, y, epochs, C, learning_rate, tolerance)
}

#' Sequential minimal optimization (SMO) algorithm for Support Vector Machines (SVM) using C++
#'
#' @param X, y of input data
#' @param C regularization parameter
#' @param tol tolerance for stopping criterion
#' @param max_passes maximum number of passes to iterate over α’s without changing
#' @return Lagrange multipliers alpha and b
#' @export
linear_kernel <- function(X1) {
    .Call(`_SVMalgo_linear_kernel`, X1)
}

svm_smo_Rcpp <- function(X, y, C = 1.0, tol = 1e-3, max_passes = 10L) {
    .Call(`_SVMalgo_svm_smo_Rcpp`, X, y, C, tol, max_passes)
}

